spring:
  datasource:
    test:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false
      mapper: classpath:mapper/test/*.xml
      username: root
      password: Mysql@local

server:
  port: 8090
  servlet:
    context-path: /demo
logging:
  level:
    root: info
    com.rnb: debug

security:
  db:
    isCrypted: false
    propertyKey:
